name: toku_flutter_learning
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  audioplayers: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/numbers/
    - assets/images/family_members/
    - assets/images/colors/
    - assets/sounds/numbers/
    - assets/sounds/family_members/
    - assets/sounds/colors/
    - assets/sounds/phrases/
